name: Build Assets

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-assets:
    name: Install and Build Package Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies for Layout
        working-directory: packages/layout
        run: npm install

      - name: Build Frontend Assets
        working-directory: packages/frontend
        run: npm run build
